import face  # though not used in this module we get circular when we omit the import
import solver as sv


# random cubes used for performance testing

f01 = 'BRDFURBBLFBLLRBFLRRDDRFUFDRLFURDDBBFUUUFLFRUUBDLLBLDUD'
f02 = 'UDBRULFLLFBDBRRDLFUFDRFULBBUDRUDULDDBDRRLFUFFLFRUBBRLB'
f03 = 'FLBRUUUUFDFDURRFLBLBLDFRUBDBLRLDUUDRUFBBLFLDRLFRDBRDBF'
f04 = 'LRLFUBRDRBUFDRFRUBFBDDFRFRBDUULDLRBLDRUDLFFFLUBBUBLULD'
f05 = 'FUDBUDRRFRRFURLLRFUBDDFLRFUBRBFDUDLRLUBLLBLDDLFUBBFUDB'
f06 = 'RFDRUDRUUFFFBRURUBBBLDFLDDUFRFUDRUDDUBDFLLBFRLLBLBRLBL'
f07 = 'RLBRUBRFLDDLURLDLUFDBRFFRRFDDLRDFUBLBFULLURBFUBDDBUFUB'
f08 = 'DUULUBLLUBDBLRDDRBFFRUFURFBFURBDDLFDFBDLLRFRULBRFBDLRU'
f09 = 'DDRLUUUBURRFDRBDBBBDFLFRUDBFFRFDLLULBURULFDRLDLLRBFUBF'
f10 = 'BBRFULRBBUBBRRRURUBRLBFDFLLRDFUDULLFLDDULDDLDUUDFBFRFF'

flist = [f01, f02, f03, f04, f05, f06, f07, f08, f09, f10]
for f in flist:
    print('Solve random cube with cube definition string ' + f)
    print(sv.solve(f))
